import Head from 'next/head'
import { REACT_MAIN_URL } from '@/config'

interface HeadBlockProps {
	h1: string
	title: string
	path: string
	page: number
	totalPages: number
}

export const HeadBlock = ({ title, path, page, totalPages }: HeadBlockProps) => {
	return (
		<Head>
			<title>{title} | Opencart React</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
			{page && +page === 1 && (
				<link href={REACT_MAIN_URL + path} rel="canonical"></link>
			)}
			{page && +page === 2 && (
				<link href={REACT_MAIN_URL + path} rel="prev"></link>
			)}
			{page && +page > 2 && (
				<link
					href={REACT_MAIN_URL + path + '?page=' + (+page - 1)}
					rel="prev"
				></link>
			)}
			{page && page < totalPages && (
				<link
					href={REACT_MAIN_URL + path + '?page=' + (+page + 1)}
					rel="next"
				></link>
			)}
		</Head>
	)
}
